Update pgrx, add postgres 16
postgresml/postgresml pull request #1093
Opened 2023-10-19 15:34 UTC by maparent

2023-10-19 15:41 UTC, maparent commented
Note: Solves #1088

2023-10-19 16:22 UTC, kczimm requested changes

2023-10-19 17:48 UTC, levkk commented
Would love to have this since Postgres just removed 16.rc1 from its FTP repo and we are breaking on `pgrx init` using 0.10.0.

2023-10-19 17:52 UTC, maparent commented on .github/workflows/ubuntu-packages-and-docker-image.yml
> -          postgresql-server-dev-15 \
apologies, near-typo.

2023-10-19 18:07 UTC, levkk commented
@maparent I'll take us all the way to pgrx 0.11.0. This will require some handholding with our CI, since you can't really our Github actions locally (requires access to our APT repo and such).

https://github.com/postgresml/postgresml/pull/1099

Thank you for the PR, mine is largely inspired by yours.

2023-10-20 13:24 UTC, closed without merging

2023-10-20 13:24 UTC, maparent commented
Superseded by https://github.com/postgresml/postgresml/pull/1102